### ISSUE TITLE
Anpassung auf Homematic mit CUxD möglich ?

### ISSUE THREAD

**Issue by PaulMerk** [jp112sdl/WemosD1_ioBroker_DS18B20#1]
Kann man dies anpassen, sodass Übertragung von (mindestens) eines Sensors vom Wemos auf ein CUxD-Gerät möglich ist wie bei den Sonoffs ?

**Comment by jp112sdl** [comment]
Siehe https://github.com/jp112sdl/WemosD1_HomeMatic_WiFiSensor
