### ISSUE TITLE
Wemos startet nicht im Konfig Modus

### ISSUE THREAD

**Issue by z0nki** [jp112sdl/WemosD1_ioBroker_DS18B20#2]
Hallo,
bei mir startet der WEMOS nach dem Flashvorgang nicht im Konfigurationsmodus. 
Wenn ich den Taster beim starten drücke leuchtet die LED kurz blau und dann für 10 Sekunden dauerhaft. Danach blinkt die LED wieder. 
Leider finde ich in dieser Zeit auch kein WLAN Signal des WEMOS. 
Nur einmal hat mir mein Handy kurz das WLAN mit der SSID: FaryLink_ED6A5F angezeigt. Konnte mich aber auch nicht darauf verbinden. 
Weiter stellt sich mir die Frage wieso der VDD des DS18B20 mit D1 verbunden wird anstatt mit dem 3v3 Pol.

Danke

**Comment by jp112sdl** [comment]
> Weiter stellt sich mir die Frage wieso der VDD des DS18B20 mit D1 verbunden wird anstatt mit dem 3v3 Pol.

Um den DS18B20 komplett vom Strom zu trennen während der Sleep-Zeit

Zu dem WLAN Problem fällt mir nix ein.
