### ISSUE TITLE
Wemos D1 mini zeigt keine Funktion

### ISSUE THREAD

**Issue by halve85** [jp112sdl/WemosD1_ioBroker_DS18B20#3]
Nach dem aufspielen des BIN zeigt mein Wemos D1 Mini nicht die gewünschte Funktion ( Licht leuchtet dauerhaft für Setup).
Benötigt er zwingend die 5V auf dem 5V Pin? Ich hatte es jetzt nur über das USB Kabel angeschlossen....

**Comment by halve85** [comment]
will ich das ganze in Arduino selber kompilieren  bleibe ich leider hier stecken:


In file included from /Users/hfu/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/sdk/libc/xtensa-lx106-elf/include/sys/stdio.h:6:0,
                 from /Users/hfu/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/sdk/libc/xtensa-lx106-elf/include/stdio.h:63,
                 from /Users/hfu/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/Arduino.h:32,
                 from sketch/WemosD1_ioBroker_DS18B20.ino.cpp:1:
/Users/hfu/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol
   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))
                                                                                                                                  ^
/Users/hfu/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:25:24: note: in expansion of macro 'PROGMEM'
 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";
                        ^
In file included from /Users/hfu/Documents/Arduino/libraries/WiFiManager/WiFiManager.h:17:0,
                 from /Users/hfu/Downloads/WemosD1_ioBroker_DS18B20-master/WemosD1_ioBroker_DS18B20/WemosD1_ioBroker_DS18B20.ino:3:
/Users/hfu/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WebServer/src/ESP8266WebServer.h:34:39: error: previous declaration of 'HTTPMethod HTTP_HEAD'
 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
                                       ^
exit status 1
Fehler beim Kompilieren für das Board LOLIN(WEMOS) D1 R2 & mini.

**Comment by jp112sdl** [comment]
Hi, sorry ich bin bei dem Thema leider schon lange raus.

**Comment by halve85** [comment]
kein Problem, habe natürlich selber weiter geschaut:
mit Version 2.3.0 des ESP8266 Board Managers in Arduino lief es dann alles...
Wieso das direkte Uploaden des BIN bei mir nicht ging, weiß ich leider nicht. Über Arduino dann alles kein Problem und alles funktioniert wie von dir beschrieben! MERCI!
